In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("insurance (1).csv")

df

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

## First model using polynomial

In [3]:
x = df[['age','bmi','children']]  # features

y = df['charges']  #target

In [4]:
from sklearn.model_selection import train_test_split

In [5]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [6]:
len(x_train)

1070

In [7]:
len(x_test)

268

In [8]:
from sklearn.preprocessing import PolynomialFeatures

In [38]:
poly1 = PolynomialFeatures(degree=2)

In [39]:
x_trainpoly = poly1.fit_transform(x_train)

x_testpoly = poly1.transform(x_test)

In [13]:
from sklearn.linear_model import LinearRegression

In [14]:
model = LinearRegression()

model.fit(x_trainpoly,y_train)

LinearRegression()

In [19]:
y_pred = model.predict(x_testpoly)

In [24]:
# model evaluation

from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error

In [21]:
r2_score(y_test,y_pred)

0.14407717923108054

In [26]:
mse = mean_squared_error(y_test,y_pred)

In [28]:
import math as m

rmse = m.sqrt(mse)

rmse

11527.399194060876

## Second model using Poly

In [31]:
df['smoker'] = df['smoker'].map({'yes':1,'no':0})
df['sex'] = df['sex'].map({'male':1,'female':0})

df.head()

   age  sex     bmi  children  smoker     region      charges
0   19    0  27.900         0       1  southwest  16884.92400
1   18    1  33.770         1       0  southeast   1725.55230
2   28    1  33.000         3       0  southeast   4449.46200
3   33    1  22.705         0       0  northwest  21984.47061
4   32    1  28.880         0       0  northwest   3866.85520

In [32]:
x = df[['age','sex','bmi','children','smoker']] # features

y = df['charges']   # target

In [33]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [40]:
poly2 = PolynomialFeatures(degree=2)

x_poly = poly2.fit_transform(x_train)
x_testpoly = poly2.transform(x_test)

In [35]:
model2 = LinearRegression()

model2.fit(x_poly,y_train)

LinearRegression()

In [36]:
y_pred2 = model2.predict(x_testpoly)

In [37]:
r2_score(y_test,y_pred2)

0.8669441556658778

In [41]:
mse = mean_squared_error(y_test,y_pred2)

mse

20656751.050439347

In [42]:
rmse = m.sqrt(mse)

rmse

4544.969862434662